PREFIX room: <https://w3id.org/dco#Room>
PREFIX was: <http://www.semanticweb.org/yasmi/ontologies/2022/2/was-ontology#>
PREFIX light: <https://w3id.org/dco#Light>
PREFIX brick: <https://brickschema.org/schema/Brick#>
PREFIX lamp: <https://saref.etsi.org/saref4bldg/Lamp#>

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?equipment WHERE {
    GRAPH <https://interactions.ics.unisg.ch/was-assignment-3-yasmine#> {
        ?subClass rdfs:subClassOf+ brick:Equipment.
        ?equipment a ?subClass.
        ?equipment brick:isPartOf room:Room.
        FILTER NOT EXISTS { ?equipment lamp:hasGoal was:Darker. }
    }
}